name: ubicameapp
description: "UbicameApp - Proyecto de GPS 2024-1"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  change_app_package_name: ^1.3.0
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_typeahead: ^4.3.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.0
  permission_handler: ^10.0.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  animated_text_kit: ^4.2.1
  flutter_spinkit: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images.png
    - assets/img-copia.jpg
    - assets/logo.png
    - .env
    - assets/video.mp4
    - assets/chatbot_logo.png
